import { defineConfig } from "vite-plus";

export default defineConfig({
    test: {
        include: ["tests/{api,uncloud,workflows,cache}/**/*.test.ts"],
        globalSetup: ["./tests/global-setup.ts"],
        setupFiles: ["./tests/setup.ts"],
    },
    lint: {
        ignorePatterns: [
            ".agent/**",
            ".agents/**",
            ".claude/**",
            ".codex/**",
            ".continue/**",
            ".cursor/**",
            ".gemini/**",
            ".opencode/**",
            ".pi/**",
            ".roo/**",
            ".windsurf/**",
            "tools/oxlint/anti-slop/**",
            "node_modules/**",
            "**/node_modules/**",
            "**/.svelte-kit/**",
            "apps/web/build/**",
            "apps/web/.output/**",
            "packages/db/dist/**",
            "packages/api/dist/**",
            "packages/auth/dist/**",
            "packages/cache/dist/**",
            "packages/s3/dist/**",
            "packages/uncloud/dist/**",
            "packages/workflows/dist/**",
            "packages/uncloud/src/generated/**",
        ],
        jsPlugins: [
            { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
            { name: "anti-slop-effect", specifier: "./tools/oxlint/anti-slop/effect/index.ts" },
        ],
        rules: {
            "oxc/no-accumulating-spread": "error",
            "anti-slop/no-array-filter-map": "error",
            "anti-slop/no-reduce-accumulator-copy": "error",
            "anti-slop/no-chained-type-assertions": "warn",
            "anti-slop/no-conditional-empty-object-spread": "warn",
            "anti-slop/no-known-value-widening": "warn",
            "anti-slop/no-module-mocking": "error",
            "anti-slop/no-object-parameters": "error",
            "anti-slop/no-reflect-apply": "error",
            "anti-slop/no-reflect-get": "error",
            "anti-slop/no-runtime-typeof": "warn",
            "anti-slop/no-shape-in-symbol-names": "error",
            "anti-slop/no-unknown-parameters": "warn",
            "anti-slop/no-unknown-returns": "warn",
            "anti-slop/no-unknown-type-aliases": "error",
            "anti-slop/no-unsafe-dictionary-type": "warn",
            "anti-slop/no-widen-then-assert": "error",
            "anti-slop/require-readable-spacing": "error",
            "anti-slop/require-safety-comment-for-type-assertion": "warn",
            "anti-slop-effect/no-manual-effect-error-tag": "error",
            "anti-slop-effect/no-manual-tag-comparison": "error",
            "anti-slop-effect/no-manual-tagged-construction": "error",
            "anti-slop-effect/no-service-constructor-imports": "error",
            "anti-slop-effect/prefer-effect-match": "warn",
        },
        options: {
            typeAware: false,
            typeCheck: false,
        },
    },
    fmt: {
        ignorePatterns: [
            ".agent/**",
            ".agents/**",
            ".claude/**",
            ".codex/**",
            ".continue/**",
            ".cursor/**",
            ".gemini/**",
            ".opencode/**",
            ".pi/**",
            ".roo/**",
            ".windsurf/**",
            "tools/oxlint/anti-slop/**",
            "node_modules/**",
            "**/node_modules/**",
            "**/.svelte-kit/**",
            "apps/web/build/**",
            "apps/web/.output/**",
            "packages/db/dist/**",
            "packages/api/dist/**",
            "packages/auth/dist/**",
            "packages/cache/dist/**",
            "packages/s3/dist/**",
            "packages/uncloud/dist/**",
            "packages/workflows/dist/**",
            "packages/uncloud/src/generated/**",
        ],
        singleQuote: false,
        semi: true,
        tabWidth: 4,
        useTabs: false,
        overrides: [
            {
                files: ["**/*.svelte"],
                options: { svelte: true, printWidth: 70, htmlWhitespaceSensitivity: "ignore" },
            },
        ],
        sortPackageJson: true,
    },
    staged: {
        "*.{js,ts,jsx,tsx,vue,svelte,json,jsonc,css,md}": "vp check --fix",
    },
});
