package httpapi

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"reflect"
	"strings"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humafiber"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/volume"
	"github.com/gofiber/fiber/v2"
	"github.com/psviderski/uncloud/pkg/api"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// The OpenAPI document is generated by Huma from the operations registered in
// registerOperations and the Go types they accept and return, so it cannot
// drift from the handlers. cmd/openapi writes it out for the TypeScript client.

// bearerSchemeName is the name of the only security scheme in the document.
const bearerSchemeName = "bearerAuth"

// publicOperation clears the document-level bearer requirement. OpenAPI needs
// an empty, non-nil list for that, so this must not be replaced with nil.
var publicOperation = []map[string][]string{}

func init() {
	// Every error keeps the sidecar's `{"error": string}` body instead of Huma's
	// RFC 9457 problem details, so clients only ever parse one error shape. It is
	// set once here because it is a package-level hook shared by every server.
	huma.NewError = newError
	// Handlers always send arrays, never null, so clients need no null checks.
	huma.DefaultArrayNullable = false
}

// Error makes ErrorResponse a huma.StatusError, so handlers can return it.
func (e *ErrorResponse) Error() string { return e.Message }

func (e *ErrorResponse) GetStatus() int { return e.status }

func newError(statusCode int, message string, errs ...error) huma.StatusError {
	// Huma reports a plain error returned by a handler as an unexpected 500.
	// Classify it instead, so Uncloud's not-found and gRPC statuses survive and
	// the caller sees the real cause.
	if statusCode == http.StatusInternalServerError && len(errs) == 1 && errs[0] != nil {
		return &ErrorResponse{status: statusForError(errs[0]), Message: errs[0].Error()}
	}

	details := make([]string, 0, len(errs))
	for _, err := range errs {
		var detail *huma.ErrorDetail
		switch {
		case errors.As(err, &detail):
			// ErrorDetail.Error() appends the rejected value, which for a body
			// error is the whole body, such as exec stdin or a Compose file with
			// credentials. Name the location only.
			details = append(details, detail.Message+" ("+detail.Location+")")
		case err != nil:
			details = append(details, err.Error())
		}
	}
	if len(details) > 0 {
		message += ": " + strings.Join(details, "; ")
	}
	return &ErrorResponse{status: statusCode, Message: message}
}

func statusForError(err error) int {
	var statusErr huma.StatusError
	if errors.As(err, &statusErr) {
		return statusErr.GetStatus()
	}
	if errors.Is(err, api.ErrNotFound) {
		return http.StatusNotFound
	}
	if code := status.Code(err); code != codes.Unknown {
		return grpcStatusCode(code)
	}
	return http.StatusInternalServerError
}

func grpcStatusCode(code codes.Code) int {
	switch code {
	case codes.InvalidArgument:
		return http.StatusBadRequest
	case codes.Unauthenticated:
		return http.StatusUnauthorized
	case codes.PermissionDenied:
		return http.StatusForbidden
	case codes.NotFound:
		return http.StatusNotFound
	case codes.AlreadyExists:
		return http.StatusConflict
	case codes.FailedPrecondition:
		return http.StatusUnprocessableEntity
	case codes.Aborted:
		return http.StatusConflict
	case codes.ResourceExhausted:
		return http.StatusTooManyRequests
	case codes.Canceled:
		return http.StatusRequestTimeout
	case codes.DeadlineExceeded:
		return http.StatusGatewayTimeout
	case codes.Unavailable:
		return http.StatusServiceUnavailable
	case codes.Unimplemented:
		// The daemon predates the RPC, e.g. domain or certificate calls on Uncloud < 0.21.
		return http.StatusNotImplemented
	default:
		return http.StatusInternalServerError
	}
}

// newAPI creates the Huma API that registers operations on app.
func newAPI(app *fiber.App) huma.API {
	config := huma.DefaultConfig("Uncloud API", "v1")
	// The default hooks add a `$schema` field and a Link header to every
	// response. The default spec and docs routes are replaced by the sidecar's
	// own, because the docs page must embed the spec rather than fetch it from
	// a route that requires the bearer token.
	config.CreateHooks = nil
	config.OpenAPIPath = ""
	config.DocsPath = ""
	config.SchemasPath = ""

	config.Info.Description = "REST API for managing Uncloud clusters. " +
		"Every endpoint except /healthz and /docs requires the sidecar's bearer token."
	config.Servers = []*huma.Server{{URL: "/", Description: "Current Uncloud API server"}}
	config.Tags = []*huma.Tag{
		{Name: "health", Description: "Liveness and readiness probes"},
		{Name: "cluster", Description: "Cluster-level information"},
		{Name: "machines", Description: "Cluster machine management"},
		{Name: "services", Description: "Service deployment and lifecycle"},
		{Name: "volumes", Description: "Docker volume management"},
		{Name: "images", Description: "Docker image inspection"},
	}
	config.Security = []map[string][]string{{bearerSchemeName: {}}}
	config.Components.SecuritySchemes = map[string]*huma.SecurityScheme{
		bearerSchemeName: {
			Type:        "http",
			Scheme:      "bearer",
			Description: "Bearer token configured through the sidecar's SIDECAR_TOKEN environment variable.",
		},
	}

	// Docker and Uncloud models are passed through untouched and documented as
	// plain objects. Reflecting them would pull hundreds of upstream schemas
	// into the contract, and ServiceSpec has no JSON tags, so every field would
	// become required. Clients parse the fields they need.
	opaque := reflect.TypeFor[map[string]any]()
	for _, passthrough := range []reflect.Type{
		reflect.TypeFor[api.ServiceSpec](),
		reflect.TypeFor[api.ServiceContainer](),
		reflect.TypeFor[volume.Volume](),
		reflect.TypeFor[image.Summary](),
		reflect.TypeFor[image.InspectResponse](),
	} {
		config.Components.Schemas.RegisterTypeAlias(passthrough, opaque)
	}

	return humafiber.NewV2(app, config)
}

// register adds an operation with the defaults every route shares.
func register[I, O any](humaAPI huma.API, op huma.Operation, handler func(context.Context, *I) (*O, error)) {
	errorStatuses := []int{http.StatusBadRequest, http.StatusNotFound, http.StatusInternalServerError}
	if op.Security == nil {
		errorStatuses = append(errorStatuses, http.StatusUnauthorized)
	}
	op.Errors = append(errorStatuses, op.Errors...)
	// Fiber already bounds reading the request with ReadTimeout and BodyLimit.
	op.BodyReadTimeout = -1
	op.MaxBodyBytes = maxRequestBodyBytes
	huma.Register(humaAPI, op, handler)
}

// eventStreamResponse documents a Server-Sent Event stream whose data payloads
// are JSON encodings of event.
func eventStreamResponse(humaAPI huma.API, description string, event any) map[string]*huma.Response {
	schema := humaAPI.OpenAPI().Components.Schemas.Schema(reflect.TypeOf(event), true, "")
	return map[string]*huma.Response{
		"200": {
			Description: description,
			Content:     map[string]*huma.MediaType{"text/event-stream": {Schema: schema}},
		},
	}
}

// bodyOutput is the output of every operation that answers with a JSON body.
type bodyOutput[T any] struct {
	Body T
}

func reply[T any](body T) *bodyOutput[T] {
	return &bodyOutput[T]{Body: body}
}

// OpenAPIDocumentJSON returns the HTTP contract without a running server, for
// cmd/openapi. The handlers are registered but never called.
func OpenAPIDocumentJSON() ([]byte, error) {
	humaAPI := newAPI(fiber.New())
	(&Server{}).registerOperations(humaAPI)
	return json.MarshalIndent(humaAPI.OpenAPI(), "", "  ")
}
